# Boolean Index

In [3]:
import numpy as np

In [4]:
age = np.random.randint(2,80,50)
age

array([15, 41, 79, 76, 35, 41, 10, 37, 23, 19, 62, 25, 18,  6,  7, 50, 58,
       60, 56, 37, 68, 73, 79, 26, 58, 26, 45,  2, 48, 76, 35, 40, 53, 56,
       12, 52, 25, 17, 28, 55, 33, 52,  4, 47, 10, 29, 40, 33, 38, 39])

In [5]:
age.min()

2

In [6]:
age.max()

79

In [7]:
age.mean()

39.08

In [8]:
len(age[age>60])

7

In [9]:
len(age[age>=18])

41

In [10]:
# How many are there between 20 to 35 years

In [13]:
len(age[(age > 20) & (age < 35)])

9

In [14]:
age

array([15, 41, 79, 76, 35, 41, 10, 37, 23, 19, 62, 25, 18,  6,  7, 50, 58,
       60, 56, 37, 68, 73, 79, 26, 58, 26, 45,  2, 48, 76, 35, 40, 53, 56,
       12, 52, 25, 17, 28, 55, 33, 52,  4, 47, 10, 29, 40, 33, 38, 39])

In [15]:
salary = np.random.randint(20000,100000,50)
salary

array([53495, 24449, 87007, 24503, 25405, 45692, 21967, 35625, 94773,
       35474, 79014, 29216, 25155, 95788, 77071, 99540, 28785, 81883,
       85830, 45298, 43482, 55610, 87247, 79536, 80509, 29014, 94355,
       71899, 91055, 59205, 78023, 63915, 68785, 58763, 59112, 83116,
       46075, 37706, 20270, 36504, 64790, 80136, 74979, 44323, 94086,
       27341, 89733, 84963, 47178, 76468])

1. What is the average salary?
2. What is the average salary of age is greater than 35?
3. What is the maximum salary of age below 40 years?
4. How many are getting salary more than 50000?
5. What is the  minimum salary of above 50 years ?
6. What is the 25% of salary?
7. What is the IQR value of Age ?

In [16]:
# 1. What is the average salary?
salary.mean()

60482.96

In [20]:
#2. What is the average salary of age is greater than 35?
salary[age>35].mean()

64214.642857142855

In [21]:
#3. What is the maximum salary of age below 40 years?
salary[age<40].max()

95788

In [18]:
#4. How many are getting salary more than 50000?
len(salary[salary>50000])

30

In [19]:
# 5. What is the  minimum salary of above 50 years ?
salary[age>50].min()

24503

In [22]:
#6. What is the 25% of salary?
np.percentile(salary,25)

36804.5

In [24]:
# 7. What is the IQR value of Age ?
Q1 = np.quantile(age, 0.25)
Q3 = np.quantile(age,0.75)
IQR = Q3-Q1
IQR

29.5

# Raven vs Flatten 

# View vs Copy

In [26]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
x = arr.copy() # Immutable
x[2] = 100
print(x)
print(arr)

[  1   2 100   4   5   6   7]
[1 2 3 4 5 6 7]


In [28]:
y = arr.view() # Mutable
y[3] = 200
print(y)
print(arr)

[  1   2   3 200   5   6   7]
[  1   2   3 200   5   6   7]


# Ravel vs Flatten

To  convert multi dimensional array (ndarray) to 1 d array

Ravel - View Version

Flatten - Copy Version 

In [30]:
arr = np.random.randint(2,20,16).reshape(1,1,4,4)
arr

array([[[[10, 10, 15, 17],
         [19,  3,  4, 13],
         [ 9, 12,  7,  5],
         [19,  2, 18,  2]]]])

In [31]:
arr.ravel()

array([10, 10, 15, 17, 19,  3,  4, 13,  9, 12,  7,  5, 19,  2, 18,  2])

In [32]:
arr.flatten()

array([10, 10, 15, 17, 19,  3,  4, 13,  9, 12,  7,  5, 19,  2, 18,  2])

In [34]:
x = arr.ravel()
x[3]=100     #  It is Mutable
print(x)
print('*'*20)
print(arr)

[ 10  10  15 100  19   3   4  13   9  12   7   5  19   2  18   2]
********************
[[[[ 10  10  15 100]
   [ 19   3   4  13]
   [  9  12   7   5]
   [ 19   2  18   2]]]]


In [36]:
y = arr.flatten()
y[-1]=1111       # It  is Immutable    
print(y)
print('*'*20)
print(arr)

[  10   10   15  100   19    3    4   13    9   12    7    5   19    2
   18 1111]
********************
[[[[ 10  10  15 100]
   [ 19   3   4  13]
   [  9  12   7   5]
   [ 19   2  18   2]]]]


# Mathematical Operations

# Constants

In [38]:
np.pi

3.141592653589793

In [39]:
np.e

2.718281828459045

In [44]:
np.inf  # Infinite

inf

In [45]:
np.array([2,1]) / 0

C:\Users\91771\AppData\Local\Temp\ipykernel_4160\770773325.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([2,1]) / 0


array([inf, inf])

In [46]:
np.nan  #Missing Value

nan

# Trigonometric Functions

In [47]:
angle = np.pi/2

In [48]:
np.sin(angle)

1.0

In [49]:
np.cos(angle)

6.123233995736766e-17

In [50]:
np.tan(angle)

1.633123935319537e+16

In [53]:
np.sec(angle)  # cot -- sec and cosec not here

AttributeError: module 'numpy' has no attribute 'sec'

In [56]:
a = np.random.uniform(2,10,16).reshape(4,4)
a

array([[3.02758747, 2.8319224 , 5.86343973, 4.44088264],
       [3.66136281, 9.20341897, 3.28476514, 9.07504345],
       [4.54369404, 3.47143856, 8.06804461, 2.72838921],
       [5.40081308, 6.11847381, 3.09349279, 3.29934683]])

In [57]:
np.round(a,1)

array([[3. , 2.8, 5.9, 4.4],
       [3.7, 9.2, 3.3, 9.1],
       [4.5, 3.5, 8.1, 2.7],
       [5.4, 6.1, 3.1, 3.3]])

In [58]:
np.ceil(a)

array([[ 4.,  3.,  6.,  5.],
       [ 4., 10.,  4., 10.],
       [ 5.,  4.,  9.,  3.],
       [ 6.,  7.,  4.,  4.]])

In [59]:
np.floor(a)

array([[3., 2., 5., 4.],
       [3., 9., 3., 9.],
       [4., 3., 8., 2.],
       [5., 6., 3., 3.]])

In [60]:
c = np.array([[-2,2],[3,-4]])
c

array([[-2,  2],
       [ 3, -4]])

In [61]:
np.abs(c)

array([[2, 2],
       [3, 4]])

# Operators on Array

In [63]:
x = np.array([[1,2],[4,5]])
y = np.array([[12,13],[14,16]])

In [64]:
x

array([[1, 2],
       [4, 5]])

In [65]:
y

array([[12, 13],
       [14, 16]])

In [66]:
x+y

array([[13, 15],
       [18, 21]])

In [67]:
x-y

array([[-11, -11],
       [-10, -11]])

In [68]:
x*y

array([[12, 26],
       [56, 80]])

In [69]:
x/y

array([[0.08333333, 0.15384615],
       [0.28571429, 0.3125    ]])

In [70]:
x//y


array([[0, 0],
       [0, 0]], dtype=int32)

In [71]:
x%y

array([[1, 2],
       [4, 5]], dtype=int32)

In [72]:
x**y

array([[          1,        8192],
       [  268435456, -2030932031]], dtype=int32)