# Day 1
### MD Tahseen Equbal 

# Installation Numpy

In [1]:
!pip install numpy

Importing

In [2]:
import numpy as np


Creaton of some Array 

In [4]:
list1 = [2,3,4,5,6]
np.array(list1)

array([2, 3, 4, 5, 6])

# Time Complexity (Speed is Less)

In [5]:
%%time
a = list(range(1,100000))

Wall time: 4.23 ms


In [6]:
%%time
arr = np.arange(1,100000)

Wall time: 0 ns


# Space Complexity (Memory)

In [7]:
import sys 

In [8]:
sys.getsizeof(a)

800048

In [10]:
sys.getsizeof(arr)

400100

# np.linspace()  --- Default is 50

In [11]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

# np.random.randint()  --- start , End , How Much 

In [14]:
np.random.randint(1,100,15)

array([81, 45, 26, 35, 60, 23, 51, 25, 29, 57, 31, 55,  4, 42, 97])

In [3]:
np.random.uniform(1,100,15)

array([35.06258702, 10.64579557, 69.19266893, 55.07193463,  7.7972095 ,
       21.58335493, 99.6073918 , 66.53613055, 50.49507365, 37.77057754,
       65.74828923, 69.62663225, 36.9596769 ,  4.75255987, 72.15612795])

# np.zeros()

In [16]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# np.ones()

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# np.full()

In [18]:
np.full((4,4),18)

array([[18, 18, 18, 18],
       [18, 18, 18, 18],
       [18, 18, 18, 18],
       [18, 18, 18, 18]])

# Attributes

In [21]:
arr1 = np.random.randint(1,20,10)


In [22]:
arr1

array([ 2,  9,  4,  1,  1,  9, 19, 13, 17,  2])

In [23]:
arr1.dtype     # Data Type of the values

dtype('int32')

In [24]:
arr1.size    # Length of the array (no of values)

10

In [25]:
arr1.itemsize   # Memory Occupied by each value

4

In [26]:
arr1.nbytes  # Total Memory occupied by the array 

40

In [27]:
arr1.ndim   # No of dimensional array

1

In [28]:
arr1.shape  # No of Rows and Column

(10,)