# Data Type 
--int  --> 8,16,32,64
--float--> 16,32,64,128
--boleean-->True,False
--complex--> Complex64
--unit (Unsigned Integr()) -->  8,16,32,64

In [5]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
arr.dtype

dtype('int32')

In [4]:
np.iinfo('int8')

iinfo(min=-128, max=127, dtype=int8)

In [7]:
np.iinfo('int32')

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [4]:
a = np.array([1,2,3,4,5,6],dtype='int8')
a


array([1, 2, 3, 4, 5, 6], dtype=int8)

# Float using

In [13]:
b = np.array([2.3,4.5,6.7,8.])

In [15]:
b.dtype

dtype('float64')

In [16]:
np.finfo('float16')

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

ValueError: data type <class 'numpy.str_'> not inexact

# astype() -- To convert One Data type to another Data Type

In [8]:
age = np.random.randint(1,120,20)
age

array([ 73, 111,  57,  83,  64,  16,  85,  49, 114,  73,  98, 101, 113,
        14,  35,  40, 119,  18,  26,  76])

In [9]:
age.dtype  # ---default int32

dtype('int32')

In [21]:
age.nbytes

80

In [22]:
ag = age.astype('int8')

In [23]:
ag.dtype

dtype('int8')

In [24]:
ag

array([108,  55,  77,  90,  53,  21,  18,  31, 102,  13, 109,  50,  59,
       102,   5, 103,  79,  37,  74,  75], dtype=int8)

In [25]:
salary = np.random.randint(30000,100000,30)

In [26]:
salary

array([69350, 60067, 66030, 59020, 57195, 84521, 85523, 95293, 75276,
       96127, 88105, 93212, 56620, 99469, 62945, 78229, 70129, 87708,
       82990, 81589, 82884, 99628, 65237, 35382, 48890, 54890, 73822,
       79116, 63063, 92445])

 # Statistical Measure

# Measure of Central Tendency

In [27]:
# Mean 
np.mean(salary)   # Function oreinted Method 

74825.16666666667

In [28]:
salary.mean()   # Object Oriented Method

74825.16666666667

In [29]:
# Median
np.median(salary)

76752.5

In [30]:
salary.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

# Measure of Dispersion

In [31]:
#Max
np.max(salary)

99628

In [32]:
salary.max()

99628

In [33]:
#Min
np.min(salary)

35382

In [34]:
salary.min()

35382

In [36]:
# Range 
range_ = np.max(salary) - np.min(salary)
range_

64246

In [37]:
#Var
np.var(salary)

257984814.20555553

In [38]:
#Standard Deviation
np.std(salary)

16061.905684119663

In [41]:
# Perncentile
np.percentile(salary,30)

64584.799999999996

In [42]:
#Quantile
np.quantile(salary,0.3)

64584.799999999996

In [43]:
# Outliers / IQR
outliers = np.quantile(salary,0.75) - np.quantile(salary,0.25)

In [44]:
outliers

24187.25

# IQR Method

In [ ]:
age = np.array([23,45,67,890,6,7,32])

Q1 = np.quantile(age,0.25)
Q3 = np.quantile(age,0.75)

IQR = Q3 - Q1

lower = max(age.min(),Q1 - 1.5 * IQR)
upper = min(age.max(),Q3 + 1.5 * IQR)

age[(age<lower) | (age>upper)]

In [49]:
def outlier(data):
    

    Q1 = np.quantile(data,0.25)
    Q3 = np.quantile(data,0.75)

    IQR = Q3 - Q1

    lower = max(data.min(),Q1 - 1.5 * IQR)
    upper = min(data.max(),Q3 + 1.5 * IQR)

    return data[(data<lower) | (data>upper)]

In [50]:
arr = np.array([1,2,3,4,5,500])

In [53]:
outlier(arr)

array([500])

# Measure of Skewness

In [54]:
salary

array([69350, 60067, 66030, 59020, 57195, 84521, 85523, 95293, 75276,
       96127, 88105, 93212, 56620, 99469, 62945, 78229, 70129, 87708,
       82990, 81589, 82884, 99628, 65237, 35382, 48890, 54890, 73822,
       79116, 63063, 92445])

In [55]:
# In Numpy Skewnees and Kurtosis is not avialiable 

# Measure of Relationship

In [11]:
age = np. random.randint([20,40,10])
age

array([10, 16,  4])

In [61]:
salary = np.random.randint([20000,40000,10])
salary

array([18483,  6774,     6])

In [62]:
np.cov(age,salary)

array([[9.3000000e+01, 6.0642000e+04],
       [6.0642000e+04, 8.7384339e+07]])

In [63]:
np.corrcoef(age,salary)

array([[1.        , 0.67269041],
       [0.67269041, 1.        ]])

# Multi Dimensional Array

In [65]:
# While Creating 

In [67]:
arr = np.array([2,3,4,5,6],ndmin = 3)
arr

array([[[2, 3, 4, 5, 6]]])

In [69]:
arr.ndim

3

In [70]:
# After Creation

In [71]:
arr = np.array([1,2,3,4,5,6])
arr.ndim

1

In [72]:
a = arr.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
a = arr.reshape(3,2,1,1)
a

array([[[[1]],

        [[2]]],


       [[[3]],

        [[4]]],


       [[[5]],

        [[6]]]])

In [74]:
a = arr.reshape(3,1,1,1)
a

ValueError: cannot reshape array of size 6 into shape (3,1,1,1)

In [76]:
a = arr.reshape(3,3,1)
a

ValueError: cannot reshape array of size 6 into shape (3,3,1)

# Indexing and Slicing

In [77]:
# Indexing - Extracting Single Value 
# Slicing - Extracting Multiple Value 

In [78]:
arr = np.array([2,3,4,5,6,7,8])

# Indexing
arr[index number/Position Number]

In [79]:
arr[3]

5

In [80]:
arr[2:5]

array([4, 5, 6])

In [26]:
ar = np.array([1,2,3,4,5,6,7,8])
ar.reshape(2,2,2,1)

array([[[[1],
         [2]],

        [[3],
         [4]]],


       [[[5],
         [6]],

        [[7],
         [8]]]])

In [27]:
ar[4:6]  # We have to go through online 

array([5, 6])

In [96]:
pip install opencv

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement opencv (from versions: none)
ERROR: No matching distribution found for opencv


In [93]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [94]:
pip install --upgrade pip

     ---------------------------------------- 2.1/2.1 MB 13.5 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Note: you may need to restart the kernel to use updated packages.


In [97]:
pip install --upgrade 24.0

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement 24.0 (from versions: none)
ERROR: No matching distribution found for 24.0
