# Set 
Unordered

Mutable

No Duplicates

no index

# Set Operation 

In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([5,6,7,8,9,10])

In [5]:
np.intersect1d(arr1,arr2)   # Common element in both arrays

array([5, 6])

In [7]:
np.union1d(arr1,arr2)    # Combining all the common Elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.setdiff1d(arr1,arr2)

array([1, 2, 3, 4])

# Sorting and Searching

In [10]:
arr = np.random.randint(2,120,10)
arr

array([ 75, 114,  89,  79, 117,  49,  64,  57,  71,  26])

In [15]:
a = np.sort(arr)
a                      # Default in Accending Order

array([ 26,  49,  57,  64,  71,  75,  79,  89, 114, 117])

In [16]:
np.flip(a)         # For reversing

array([117, 114,  89,  79,  75,  71,  64,  57,  49,  26])

In [17]:
np.sort(arr)[::-1] 

array([117, 114,  89,  79,  75,  71,  64,  57,  49,  26])

In [18]:
arr.max()

117

In [19]:
arr.argmin()

9

In [20]:
arr

array([ 75, 114,  89,  79, 117,  49,  64,  57,  71,  26])

In [22]:
arr.argsort()    # It return the indices of the Sorted Value 

array([9, 5, 7, 6, 8, 0, 3, 2, 1, 4], dtype=int64)

# LinearAlgebra 

## Solving Linear Equation

x+2y = 3

2x-3y = 9

In [25]:
a = np.array([[1,2],[2,-3]])  # It is for LHS in 2d  --- Its a input work
b = np.array([[3],[9]])       # It is for RHS in 2d  --- Its a Output Work

In [26]:
np.linalg.solve(a,b)

array([[ 3.85714286],
       [-0.42857143]])

Q 2

x + 3y -2z =-19

3x - 9y+ z = 2

5x + 10y + 10z =100

In [37]:
a =  np.array([[1,3,-2],[3,-9,1],[5,10,10]])
a

array([[ 1,  3, -2],
       [ 3, -9,  1],
       [ 5, 10, 10]])

In [38]:
b = np.array([[-19],[2],[100]])
b

array([[-19],
       [  2],
       [100]])

In [39]:
np.linalg.solve(a,b)

array([[-0.92307692],
       [ 0.56923077],
       [ 9.89230769]])

# Q4 
10a+20b-3c+4d-20e = 22
2a+120b+23c-20e = 222
a+20b+13c+4d-2e = 10
20b-3c+4d =1
30 a +4c = 22

In [46]:
A = np.array([
    [10, 20, -3, 4, -20],
    [2, 120, 23, 0, -20],
    [1, 20, 13, 4, -2],
    [0, 20, -3, 4, 0],
    [30, 0, 4, 0, 0] ])



In [70]:
B = np.array([22, 222, 10, 1, 22])

In [71]:
x = np.linalg.solve(A,B)
x

array([ 0.67583333,  1.63739931,  0.43125   , -7.61355903, -0.71208333])

In [72]:
np.linalg.det(A)

4607999.999999989

# Det = ad - bc [[a,b],[c,d]]

In [62]:
arr2 = ([[1,2],
         [2,-3]])

In [63]:
np.linalg.det(arr2)

-7.000000000000001

# Matrix  and Array

In [73]:
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[3,4],[7,9]])

In [74]:
a*b

matrix([[17, 22],
        [37, 48]])

In [77]:
x = np.array([[1,2],[3,4]])
y = np.array([[3,4],[7,9]])

In [78]:
x*y

array([[ 3,  8],
       [21, 36]])

# Identity Matrix

In [79]:
np.identity(3)     # It gives Squared Matrices

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
 np.eye(3,3)  # It gives any shape

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Eigen Value and Eigen Vectors 

In [83]:
a = np.array([[2,3,4],[4,1,8],[7,9,1]])
a

array([[2, 3, 4],
       [4, 1, 8],
       [7, 9, 1]])

In [84]:
np.linalg.eig(a)

(array([13.        , -1.29843788, -7.70156212]),
 array([[-0.41294832, -0.79524162, -0.11292499],
        [-0.59648091,  0.5579114 , -0.64384884],
        [-0.6882472 ,  0.23733022,  0.75677383]]))

In [85]:
eig_val,eig_vect = np.linalg.eig(a)

In [86]:
eig_val

array([13.        , -1.29843788, -7.70156212])

In [87]:
eig_vect

array([[-0.41294832, -0.79524162, -0.11292499],
       [-0.59648091,  0.5579114 , -0.64384884],
       [-0.6882472 ,  0.23733022,  0.75677383]])

# Joining Arrays 

In [88]:
arr1 = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
arr2 = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)
arr2
                                                  

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [92]:
np.concatenate((arr1,arr2))  # By default axis =0

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [93]:
np.concatenate((arr1,arr2),axis = 0)  # axis =0 row wise that means rows increasing

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [98]:
np.concatenate((arr1,arr2),axis = 1)  # axis =1 column wise that means column increases


array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

# Stacking

In [96]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [99]:
np.hstack((arr1,arr2))                          # H- horizontal like axis = 1

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

In [101]:
np.vstack((arr1,arr2))                      # V- Vertically like axis = 0

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [103]:
np.dstack((arr1,arr2))                       # D- Depth Wise 

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30],
        [ 4, 40]],

       [[ 5, 50],
        [ 6, 60],
        [ 7, 70],
        [ 8, 80]]])