### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [7]:
### code here

# Create arrays
zeros_array = np.zeros(10)
print(" An array of 10 zeros :\n", zeros_array)
ones_array = np.ones(10)
print(" An array of 10 ones :\n", ones_array)
fives_array = np.ones(10) * 5
print(" An array of 10 Fives :\n", fives_array)


 An array of 10 zeros :
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 An array of 10 ones :
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 An array of 10 Fives :
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
## sample output

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [8]:
### code here
array_30_to_70 = np.arange(30, 71)
print(' Array of the Integers from 30 to 70 :\n',array_30_to_70)

 Array of the Integers from 30 to 70 :
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
### sample output

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [9]:
### code here
even_array = np.arange(10, 51, 2)
print("Array of all the Even Integers from 10 to 50 :\n",even_array)

Array of all the Even Integers from 10 to 50 :
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
## sample output


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [10]:
### code here
identity_matrix = np.eye(3)
print("3x3 matrix :\n",identity_matrix)

3x3 matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## sample output

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [11]:
### code here
# Generate a random number between 0 and 1
random_number = np.random.random()
print("Random number between 0 to 1 :\n",random_number)

Random number between 0 to 1 :
 0.6617591859068525


In [ ]:
## sample output

Random number between 0 and 1:
[0.40400053]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [12]:
## code here
# Generate an array of 15 random numbers from a standard normal distribution
random_numbers = np.random.normal(size=15)
print("15 random numbers from a standard normal distribution :\n",random_numbers)

15 random numbers from a standard normal distribution :
 [-0.90544287  1.28118641  0.07067273  0.87632795  1.40930311  0.19384172
 -1.33987414 -0.09195817 -0.02582277 -0.8688911  -1.88901987  0.26881093
 -0.27375482  0.09150543 -0.87441605]


In [ ]:
## sample output

15 random numbers from a standard normal distribution:
[ 0.68439314  1.50916987 -0.75364839  0.1038106   0.07789927 -0.15349755
  1.78151615  0.49989426  0.18791322 -1.51931266 -0.55512066  2.02808972
  0.37648568  0.57999878 -0.31095957]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [15]:
## code here
# Create a 3x4 array
array_3x4 = np.array([[10, 11, 12, 13],
                      [14, 15, 16, 17],
                      [18, 19, 20, 21]])
print("Original array :\n",array_3x4)

# Iterate over the array
print("Each element of the array is:")
for row in array_3x4:
    for element in row:
        print(element, end=" ")
print()

Original array :
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 


In [ ]:
## sample output

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [16]:
## code here
# Define two vectors
vector1 = np.array([1, 8, 3, 5])
print("vector-1\n")
vector2 = np.array([10, 1, 4, 10])
print("vector-2\n")

# Multiply the values of the two vectors
result = vector1 * vector2

print("Multiply the values of two said vectors:\n", result)

vector-1

vector-2

Multiply the values of two said vectors:
 [10  8 12 50]


In [ ]:
## sample output

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [17]:
### code here
# Create an array
array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
 36, 37])


# Reverse the array
reversed_array = np.flip(array)

print("Original array:\n", array)
print("Reversed array:\n", reversed_array)

Original array:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array:
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [ ]:
## sample output

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [18]:
## code here
# Create a 5x5 zero matrix
zero_matrix = np.zeros((5, 5))

# Assign values 1, 2, 3, 4, 5 to the main diagonal
np.fill_diagonal(zero_matrix, [1, 2, 3, 4, 5])

print(zero_matrix)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [ ]:
## sample output

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [22]:
## code here
# Create a sample array
array = np.array([[0, 1],
                  [2, 3],
                  ])

# Compute the sum of all elements
total_sum = np.sum(array)

# Compute the sum of each column
column_sums = np.sum(array, axis=0)

# Compute the sum of each row
row_sums = np.sum(array, axis=1)

print("Original array:")
print(array)
print("Sum of all element:\n", total_sum)
print("Sum of each Columns:\n", column_sums)
print("Sum of each Rows:\n", row_sums)

Original array:
[[0 1]
 [2 3]]
Sum of all element:
 6
Sum of each Columns:
 [2 4]
Sum of each Rows:
 [1 5]


In [ ]:
## sample output

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [25]:
## code here

# Define two vectors
vector1 = np.array([4, 5])
vector2 = np.array([7, 10])
print("Original vectors :\n",vector1)
print(vector2)

# Compute the inner product using np.dot()
inner_product = np.dot(vector1, vector2)

# Alternatively, you can use the @ operator
# inner_product = vector1 @ vector2

print("Inner product of the said vectors:\n", inner_product)

Original vectors :
 [4 5]
[ 7 10]
Inner product of the said vectors:
 78


In [ ]:
## sample output

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
