### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [7]:
# Original array
original_array = np.array([[ 3.,  2., np.nan,  1.],
                           [10., 12., 10.,   9.],
                           [ 5., np.nan,  1., np.nan]])

print("Original array:")
print(original_array)

# Find the missing data in the array
missing_data = np.isnan(original_array)

print("\nFind the missing data of the said array:")
print(missing_data)

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [4]:
### code here
# Define two sample arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([1, 2, 3, 4, 5])

# Check if arrays are equal element-wise
are_equal = np.array_equal(array1, array2)
if are_equal:
    print("The arrays are equal element-wise.")
else:
    print("The arrays are not equal element-wise.")

The arrays are equal element-wise.


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [6]:
# Original array
original_array = np.array([[ 0,  1,  2,  3],
                           [ 4,  5,  6,  7],
                           [ 8,  9, 10, 11],
                           [12, 13, 14, 15]])

print("Original array:")
print(original_array)

# Create a new array by swapping first and last rows
swapped_array = original_array.copy()  # Make a copy to preserve the original array
swapped_array[[0, -1]] = swapped_array[[-1, 0]]

print("\nArray after swapping first and last rows:")
print(swapped_array)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Array after swapping first and last rows:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [8]:
#### code here
# Convert a list to a NumPy array
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)

print("Array from list:")
print(array_from_list)

# Convert a tuple to a NumPy array
tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)

print("\nArray from tuple:")
print(array_from_tuple)

Array from list:
[1 2 3 4 5]

Array from tuple:
[ 6  7  8  9 10]


###### 5. Write a NumPy program to find common values between two arrays.

In [9]:
### code here
# Define two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common values between the two arrays:")
print(common_values)

Common values between the two arrays:
[3 4 5]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [11]:
# Original arrays
array1 = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Original 3x2 array:")
print(array1)

print("\nReshaped to 2x3:")
reshaped_array1 = np.reshape(array1, (2, 3))
print(reshaped_array1)

print("\nOriginal 2x3 array:")
print(array2)

print("\nReshaped to 3x2:")
reshaped_array2 = np.reshape(array2, (3, 2))
print(reshaped_array2)

Original 3x2 array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]

Original 2x3 array:
[[1 2 3]
 [4 5 6]]

Reshaped to 3x2:
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [12]:
### code here

# Original array
original_array = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])

print("Original array:")
print(original_array)

# Get unique values and their counts
unique_values, counts = np.unique(original_array, return_counts=True)

# Create an array with unique values and their frequencies
frequency_array = np.array([unique_values, counts])

print("\nFrequency of unique values of the said array:")
print(frequency_array)

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]

Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [13]:
### code here
# Original arrays
array1 = np.array([[0, 0, 0],
                   [1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([10, 11, 12])

print("Array-1:")
print(array1)

print("\nArray-2:")
print(array2)

# Expand dimensions of array2 to match the shape of array1
expanded_array2 = np.expand_dims(array2, axis=0)

# Perform broadcasting and addition
result = array1 + expanded_array2

print("\nNew Array:")
print(result)

Array-1:
[[0 0 0]
 [1 2 3]
 [4 5 6]]

Array-2:
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [14]:
### code here
# Original array
original_array = np.array([[ 0,  1,  2,  3],
                           [ 4,  5,  6,  7],
                           [ 8,  9, 10, 11],
                           [12, 13, 14, 15]])

print("Original array:")
print(original_array)

# Extract the second row
second_row = original_array[1]

print("\nExtracted data: Second row")
print(second_row)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [15]:
## code here
# Original array
original_array = np.array([[ 0,  1,  2,  3],
                           [ 4,  5,  6,  7],
                           [ 8,  9, 10, 11],
                           [12, 13, 14, 15]])

print("Original array:")
print(original_array)

# Extract third and fourth elements of the first and second rows
extracted_data = original_array[:2, 2:]

print("\nExtracted data: Third and fourth elements of the first and second rows")
print(extracted_data)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [16]:
### code here
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Convert dates to NumPy datetime64 format
today_np = np.datetime64(today)
yesterday_np = np.datetime64(yesterday)
tomorrow_np = np.datetime64(tomorrow)

print("Yesterday:", yesterday_np)
print("Today:", today_np)
print("Tomorrow:", tomorrow_np)

Yesterday: 2024-05-29
Today: 2024-05-30
Tomorrow: 2024-05-31


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [18]:
## code here
# Define the date range for May 2017
start_date = np.datetime64('2017-05-01')
end_date = np.datetime64('2017-05-31')

# Find the first Monday in May 2017
first_monday = np.busday_offset(start_date, 0, roll='forward', weekmask='Mon')

print("The first Monday in May 2017:\n", first_monday)

The first Monday in May 2017:
 2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
